### ISSUE TITLE
Invisible recaptcha reactive forms

### ISSUE THREAD

**Issue by pasblin** [Enngage/ngx-captcha#101]
Hi, 

Using reactive forms with invisible recaptcha im getting this error:

**Expected validator to return Promise or Observable.**

`this.registerForm = this.fb.group({
 recaptcha: ['', Validators.required]
    });`

` <ngx-invisible-recaptcha [siteKey]="captachaKey"  formControlName="recaptcha">
  </ngx-invisible-recaptcha>`

Regards.

**Comment by mcastilleja** [comment]
Hi, sorry if you found a solution to the problem? well I have the same problem.

Regards.

**Comment by pasblin** [comment]
Hi, nope, I'm still waiting for a solution....

**Comment by Enngage** [comment]
@pasblin Based on the error message it seems you are incorrectly adding validators. Please check your code based on this https://stackoverflow.com/questions/50548062/expected-validator-to-return-promise-or-observable 

I'm closing this now as I don't think this is a problem with this library. Will reopen only if proven otherwise.
