### ISSUE TITLE
New version can fail builds

### ISSUE THREAD

**Issue by Triplecorpse** [Enngage/ngx-captcha#13]
After last update that was ~3 hours ago, out test server fall with error

![image](https://user-images.githubusercontent.com/11461770/42808370-de4174e6-89bb-11e8-8e17-0585c8b51ccc.png)

Have to notice that local build with reinstalling node_modules passed successfull. The issue reproduced on test server only. Need to set strict 3.1.0 version.

**Comment by Enngage** [comment]
Hi, I'm using exactly same build as for previous 3.x builds using the `ng-packgr` and the only thing I changed between 3.1.0 and 3.1.1 is literally only using different property. I would think that this is caused by something else. You said that local install succeded, right? Can you try new install on your server as well?

**Comment by Triplecorpse** [comment]
Watched your commit.
Very strange because I use recaptcha2 only and you made changes to invisible captcha. On the other hand, our server didn't see package at all. If there was some bug in the code, server would say that I won't run this shit but not that cannot find.
Our devops tried to install manually: cleaned the folder, cloned our repo, make npm install and run but shit still happens.

**Comment by Enngage** [comment]
Ah, sorry man.. This was my mistake.. I'm maintaining dozens of packages both public and private and forgot to run proper publish script.  Can you try `3.1.2`? Thanks!

**Comment by Triplecorpse** [comment]
Works fine. Happy with that. Have a nice day!
