### ISSUE TITLE
The example https://enngage.github.io/ngx-captcha/ does not reflect change in language code

### ISSUE THREAD

**Issue by Amit-Ag** [Enngage/ngx-captcha#135]
1. Go to the example hosted https://enngage.github.io/ngx-captcha/
2. Enter language as  'hi' or any other supported language code
3. The Captcha is still seen in english
4. Expected the Captcha text should be localised a per the language code

**Comment by kghouri0** [comment]
Exactly the same issue I have been facing

**Comment by Enngage** [comment]
Yes, seems like there was some internal change on Google's side and I'm unable to change the language once reCaptcha was loaded. You can still set the language, but it will only be reflected on the first load. Also, I would probably recommend to not set the language at all because Google will automatically use the language of the browser for recaptcha.
