### ISSUE TITLE
forRoot problem v5.0.2

### ISSUE THREAD

**Issue by alainbelez** [Enngage/ngx-captcha#24]
I just updated to 5.0.2 from 4.0.1 and i am experiencing this

```
ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'NgxCaptchaModule' was called.
src/app/app.module.ts(62,22): error TS2339: Property 'forRoot' does not exist on type 'typeof NgxCaptchaModule'.
```

**Comment by Enngage** [comment]
Hi,

Yes, that is expected because the forRoot method has been removed in 5.x.y release because siteKeys can now only be configured on component level with `siteKey` property as mentioned in release -> https://github.com/Enngage/ngx-captcha/releases/tag/5.0.2 

Closing. Feel free to reopen if you find another issue.
