### ISSUE TITLE
Breaks inside Modal

### ISSUE THREAD

**Issue by Worthy7** [Enngage/ngx-captcha#25]
This doesn't happen every time, but about 10% of the time the page loads, and when I open my modal with the login form, the Captcha is not initialized properly.

I believe this might be because it is initialized with the component? Which is only initialized when the modal is opened?

![image](https://user-images.githubusercontent.com/4762399/45791972-d0f40680-bcc6-11e8-8174-7e08c4b2cd46.png)

The error says:  reCAPTCHA cannot be read, please check your internet connection and refresh.

reCAPTCHA を読み込めませんでした。インターネット接続を確認して reCAPTCHA を再読み込みしてくだ

Does anyone know about this problem?

**Comment by Enngage** [comment]
The captcha is registering google script only once its initialized in the component. I guess dialog components have 'different' behavior which is preventing this to work correctly. I would recommend trying 2 options:

1) Include google script manually on your homepage (captcha should figure out that script is available and should work all the time)
2) Put captcha on your component and hide it with CSS so that the script is initialized. Do this in your 'standard' component rather then dialog one.

**Comment by Worthy7** [comment]
Cheers, I'll give it a go

**Comment by Enngage** [comment]
I believe the above is the proper way of handling this. Feel free to reopen if necessary.
