### ISSUE TITLE
Is it possible to do server side validation?

### ISSUE THREAD

**Issue by elieobeid7** [Enngage/ngx-captcha#37]
If so how? Assuming Recaptcha is installed on the client side using ngx-recaptcha and on the server side using some library

**Comment by Enngage** [comment]
Yes, it is possible - actually its necessary as otherwise the validation is pretty much meaningless. When captcha succeeds, it gives you a token. You then need to POST this token to your server and validate as per google - see [https://developers.google.com/recaptcha/docs/verify](https://developers.google.com/recaptcha/docs/verify)
