### ISSUE TITLE
Problem with ReCaptcha V3

### ISSUE THREAD

**Issue by andreaf91** [Enngage/ngx-captcha#71]
I am getting the following error for reCaptcha V3.
This error appears in the console:

Uncaught TypeError: grecaptcha.execute(...).then(...).catch is not a function
    at ngx-captcha.js:1375
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
    at NgZone.push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular (core.js:17258)
    at ScriptService.onRegister (ngx-captcha.js:1355)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:17299)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:387)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:138)
    at NgZone.push../node_modules/@angular/core/fesm5/core.js.NgZone.run (core.js:17213)

**Comment by Enngage** [comment]
I have no idea what you are doing, but its working fine in demo. Please have a look at https://github.com/Enngage/ngx-captcha/blob/master/demo/src/re-captcha-3-demo.component.ts and try to replicate it on your end. I'm closing this because there is nothing to go on.

**Comment by andreaf91** [comment]
![image](https://user-images.githubusercontent.com/36422774/75165174-f8d36f00-56ef-11ea-9efa-14617efbec4d.png)

**Comment by Enngage** [comment]
I see, thats odd since the actual token is fetched correctly.. will have a look when I have some time.

**Comment by fabioseno** [comment]
Apparently the error happens on the second execution.

**Comment by felipeplets** [comment]
For me it happens always, the issue seems that the `grecaptcha` from Recaptcha `https://www.gstatic.com/recaptcha/releases/61bII03-TtCmSUR7dw9MJF9q/recaptcha__en.js` on projects/ngx-captcha-lib/src/lib/services/recaptcha_v3.service.ts line 50 is assuming the return is a promise and thus assigning `then` and `catch` values, but if you look the code on the library it's like this: 
```js
    function U$(y, A) {
        return {
            then: function(d, M) {
                return (void 0 === A || A.has(xQ) || A.set(xQ, d),
                U$)(y.then(d, M), A)
            }
        }
    }
```

So it does not return a promise, it only has a then method. 

Also if you check the documentation on: https://developers.google.com/recaptcha/docs/v3 it only shows the method `then` and never a method `catch`.

I'll send a PR removing the catch method and adding a try/catch.

**Comment by Enngage** [comment]
I've released a fix from @felipeplets  PR, see if that helps :-)

**Comment by felipeplets** [comment]
I've just updated and the fix works for me! Thanks @Enngage!

**Comment by andreaf91** [comment]
The fix works for me too. Thank you  @Enngage  @felipeplets
